### ISSUE TITLE
Slack Notifier not implemented yet

### ISSUE THREAD

**Issue by fdocr** [fdoxyz/martilla#1]

**Comment by anoopmadhav** [comment]
Can you assign me on this ?

**Comment by fdocr** [comment]
Sure! You can give this a try anytime and send in a PR.

The Slack notifier class is already [here](https://github.com/fdoxyz/martilla/blob/master/lib/martilla/notifiers/slack.rb) ready to be implemented. You can take a look at other notifiers and ask me if you have any questions about this.
