### ISSUE TITLE
Cannot upload to s3 bucket main folder

### ISSUE THREAD

**Issue by Glorf** [fdoxyz/martilla#17]
Another issue:

I upload my backups to s3 bucket. Initially I wanted to put it into the main catalogue of bucket, but there seems to be no way to do it. When I provide no folder, the backup files are created in `./` catalogue. When i put `/` in front of file name, the things go all weird and the backups go to the catalogue with empty name (sic!)

Please, fix it, so that when you just provide the file name, the backup file goes to the main bucket folder by default

**Comment by fdocr** [comment]
Release `v0.4.0` should include the fix to this problem
